[tool.pyflow]
name = "Chem"
py_version = "3.8"
version = "0.0.1"
author = "David O'Connor"

[tool.pyflow.scripts]
h1 = "prototype1d:plot_h_static"
h1e = "prototype1d:plot_h_evolve"
h1de = "prototype1d:plot_h_evolve_de"
h2 = "prototype2d:plot_h_static"
h3 = "prototype1d:plot_h_sph"
op = "op:main"

[tool.pyflow.dependencies]
ipython = { version = "^7.18.1", extras = ["qtconsole"] }
matplotlib = "^3.3.2"
numpy = "^1.19.2"
scipy = "^1.5.2"
pyqt5 = "^5.13.0"
qtconsole = "^4.5.5"
plotly = "^4.5.2"

# todo how to properfly install fenics?
#fenics = "^2019.1.0"
#fenics-ffc = "^2019.1.0"


# for sfepy, which isn't on pypi. Pyflow currenlty
#sfepy = { path = "/home/david/Desktop/sfepy-wheel" }
#mayavi = { path = "/home/david/Desktop/mayavi-wheel" }
#configobj = "^5.0.6"  # Not specified by myavi's METADATA.




[tool.pyflow.dev-dependencies]

